version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 9977:3306
    environment:
      - MYSQL_ROOT_PASSWORD=testrootpassword
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword